/*
 * Copyright © 2022, Medelför OÜ. All rights reserved.
 * For any additional information refer to https://medelfor.com
 */

#ifndef MODULE_PROCESSOR_INCLUDE_UDOCS_PROCESSOR_VERSION_H_
#define MODULE_PROCESSOR_INCLUDE_UDOCS_PROCESSOR_VERSION_H_

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_INDEX 2
#define VERSION_TAG ""
#define VERSION_BUILD 41
#define VERSION_BUILD_ID "18298e01-025c-4157-871b-95a9cf3d6a9d"
#define VERSION_BUILD_TIMESTAMP 1686517878

#endif  // MODULE_PROCESSOR_INCLUDE_UDOCS_PROCESSOR_VERSION_H_
